### ISSUE TITLE
presence and multiple neovim instances/ tmux

### ISSUE THREAD

**Issue by danielpieper** [andweeb/presence.nvim#1]
I really like this plugin! It works great out of the box.

I'm using tmux to handle multiple projects and i'm switching between them constantly.
It seems like presence reports only from the neovim instance which was started first.

**Comment by andweeb** [comment]
Thanks @danielpieper, I appreciate it!

The plugin handles only the `BufRead` autocommand for now. I'm planning on adding more events (e.g. `TextChanged` and `TextChangedI`), but with just `BufRead` your activity should be set in Discord any time a new buffer is opened, whether it's from the original Neovim instance or in a new instance in a new pane.

Is your issue the former with needing more autocmds (feature) or the latter with your activity not being set in new instance (bug)?

**Comment by danielpieper** [comment]
Got it, so the reason the status sometimes is not updated is just because i'm switching neovim instances without opening other buffers.
I'm fine with this behavior but would of course wish for the added events (feature)

**Comment by andweeb** [comment]
For sure! It would take some time due to the complexity of synchronizing Neovim instances and introducing debouncing logic for those `TextChanged` events, but I can give it a shot when I'm free.

**Comment by andweeb** [comment]
Hi @danielpieper, I've just pushed some big changes to support updating Rich Presence across multiple Neovim instances!

With the latest update, you should now be able to see the following behavior:
- Rich Presence will update when edits are made to a file, debounced by default on `TextChanged` events
- The timestamp is now set to when a buffer in the workspace was first opened, and it will persist throughout any buffer activity in other Neovim instances, until the last buffer in the workspace is closed
- When exiting Neovim, activity will be set for another open buffer if available

Let me know if you run into any problems, and if not feel free to  close out this issue if it looks good. Thanks!

**Comment by andweeb** [comment]
Seems like it's been working fine :) I'll close this out!

**Comment by Gilgames000** [comment]
Hey! Loving the plugin so far. The only issue I'm having is that the presence is not updating when I switch to another vim instance in a different tmux session even after editing a file. Did I misunderstand how this should work? If I close the first vim instance I opened the presence updates accordingly though. Thanks!
