### ISSUE TITLE
Ability of change discord image state 

### ISSUE THREAD

**Issue by SIGMazer** [andweeb/presence.nvim#102]
I tried to change `main_image` in plugin configuration but it does not work, can we have the ability to add custom image.

**Comment by melonges** [comment]
same question

**Comment by melonges** [comment]
@SIGMazer https://github.com/andweeb/presence.nvim/issues/94
its not possible

**Comment by SIGMazer** [comment]
@melonges 
i think we can if we edit  `file_asseds.lua` 
but the problem is how to make the url image that i put it in setup be the default 
i'll try to open PR
#106

**Comment by SIGMazer** [comment]
now the question how to make the image i want is the default
