### ISSUE TITLE
[Void Linux] Failed to determine Discord IPC socket path

### ISSUE THREAD

**Issue by nemesissp** [andweeb/presence.nvim#105]
maybe my distro is not supported

![presence-error](https://user-images.githubusercontent.com/64988539/236648767-e87d095f-7431-4c84-88d2-d04690c40ea5.png)

**Comment by nemesissp** [comment]
One solution that might solve compatibility across all operating systems is to use the WebSocket transport method instead of IPC.

**Comment by jiriks74** [comment]
Hello,
if you're willing to transfer your issue to [my repo](https://github.com/jiriks74/presence.nvim) I'll try to take a look at it.

I cannot make any promises as I don't know how much free time I'll have and I have just started working with Lua but I'll try my best to solve it.

---

[I can see that websockets] are possible with Discord so I think that it's possible to implement. However it would probably still need IPC socket as a fallback. I'd neet to figure out whether Flatpak Discord supports this.

Also: What is your `XDG_RUNTIME_DIR` set to? On most distros it points to `/run/user/$UID` and there should be either `discord-ipc-0` or `app/com.discordapp.Discord/discord-ipc-0` if you use Flatpak.

**Comment by xbz-24** [comment]
same thing for me

![image](https://github.com/andweeb/presence.nvim/assets/68678258/b4b04811-78f2-4c4a-9f7a-34f1f0b2c4f0)

**Comment by nemesissp** [comment]
Hello, I found a way to solve this, the problem is that the plugin was not finding the Discord IPC file, I saw in the code that it was looking for some folders, this includes the TMP, XDG_RUNTIME_DIR and another one that I don't remember, for some reason the plugin couldn't find it in the TMP folder, my solution was to add a new environment variable: XDG_RUNTIME_DIR=/tmp, I edited the .bashrc file and put the following: export XDG_RUNTIME_DIR=/tmp

**Comment by jiriks74** [comment]
I don't know if I'd recommend setting the variable to `/tmp`. It should be set by `pam_systemd`: https://wiki.archlinux.org/title/XDG_Base_Directory#User_directories

**Comment by xbz-24** [comment]
true, but I am not running arch but artix (no systemd) also I tried setting the env var to /tmp (and I also did source ~/.bashrc)but still didnt found the socket path, any other idea guys?

**Comment by xbz-24** [comment]
what, I did :messages inside neovim and found a different log
(after I did export XDG_RUNTIM_DIR = /tmp with source ~/.bashrc)
![image](https://github.com/andweeb/presence.nvim/assets/68678258/62cc9791-f4c4-4f0a-9527-e3368a6af963)

**Comment by jiriks74** [comment]
> true, but I am not running arch but artix (no systemd) also I tried setting the env var to /tmp (and I also did source ~/.bashrc)but still didnt found the socket path, any other idea guys?

Try to run `find $XDG_RUNTIME_DIR -name discord-ipc-0` to see if discord even creates the socket.

**Comment by jiriks74** [comment]
@Xbz-24 Would you please send me the output?
