### ISSUE TITLE
Does not work for .d files

### ISSUE THREAD

**Issue by jtbx** [andweeb/presence.nvim#107]
### Description

The rich presence does not work for D files.

### Neovim version

```markdown
NVIM v0.8.3
```

### OS information

Gentoo

### Steps to reproduce

Run `nvim test.d`

### Logs

.

**Comment by jiriks74** [comment]
Hello,
if you're willing to transfer your issue to [my repo](https://github.com/jiriks74/presence.nvim) I'll try to take a look at it.

I cannot make any promises as I don't know how much free time I'll have and I have just started working with Lua but I'll try my best to solve it.

---

I could reproduce this. Maybe a filetype is missing?

**Comment by jtbx** [comment]
I use Emacs now, works much better out of the box
