### ISSUE TITLE
rpc error

### ISSUE THREAD

**Issue by jbgy** [andweeb/presence.nvim#120]
### Description

The RPC wont start

### Neovim version

```markdown
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### OS information

macOS ventura 13.4

### Steps to reproduce

1. start nvim

### Logs

Error executing vim.schedule lua callback: ...ocal/share/nvim/lazy/presence.nvim/lua/presence/init.lua:358: attempt to index local 'response' (a nil value)                                                                                                                           
stack traceback:
        ...ocal/share/nvim/lazy/presence.nvim/lua/presence/init.lua:358: in function 'on_done'
        ...l/share/nvim/lazy/presence.nvim/lua/presence/discord.lua:186: in function <...l/share/nvim/lazy/presence.nvim/lua/presence/discord.lua:185>

**Comment by haShinui** [comment]
Exactly the same problem here.
Running Hyprland, Arch on nvim with nvchad
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by jbgy** [comment]
@haShinui it got fixed
