### ISSUE TITLE
Actual Documentation like how tf do I rice

### ISSUE THREAD

**Issue by OxidizedToast** [andweeb/presence.nvim#137]
**Is your feature request related to a problem? Please describe.**
Little documentation so its hard to rice

**Describe the solution you'd like**
more &or actual documentation

**Describe alternatives you've considered**
Not ricing and just using it but i want rice

**Additional context**
None

**Comment by juni-purr** [comment]
https://github.com/andweeb/presence.nvim?tab=readme-ov-file#configuration ?

**Comment by OxidizedToast** [comment]
I'm sorry at the time of this I was brain dead and was a newbie to ricing and forgot abt this. So sry and I'm no long a idiot
