### ISSUE TITLE
[Bug] Presence does not show up on Discord on initial nvim startup

### ISSUE THREAD

**Issue by hypadr1v3** [andweeb/presence.nvim#19]
Hi,
I recently installed `presence.nvim` on Neovim v0.5.0-dev+1354-ga282a177d. Running `:messages` gave me no visible errors and indicated that everything is working properly but when actually coming onto discord, no presence can be seen.

Here's my `:messages`:

![image](https://user-images.githubusercontent.com/37071813/120781710-bf202380-c542-11eb-8826-99b9f86afbad.png)

Here's what is happening on Discord:

![image](https://user-images.githubusercontent.com/37071813/120782336-57b6a380-c543-11eb-8f08-ba6ef0a4d4df.png)

Any ideas on fixing it or at least debugging what went wrong?

**Comment by andweeb** [comment]
Hi @hypadr1v3! Hmm that's interesting, nothing really pops out to me as suspicious in your logs.

Looks like I might need some more info:
* What OS are you using? (Ubuntu?)
* Mind sharing your `init.vim`/`.vimrc`? Or at least your NERDTree configuration?

**Comment by hypadr1v3** [comment]
I am using Windows 10 Version 2004.

My `init.vim` is long and just a lot of configs frankensteined together so its [here](https://pastebin.com/YZDN4bh0) in a pastebin

**Comment by hypadr1v3** [comment]
I'm sorry for any trouble, this actually seems to be a bug from discord's side. Discord gives me no indication that it is working, but for everyone else, my status can be shown. I also noticed that using neovim on `cmd` gives me a different set of issues where it doesn't detect any socket address for my neovim session. I'll leave this open until it is figured out what exactly is causing both these issues. 

![image](https://user-images.githubusercontent.com/37071813/120880138-d6621e00-c5e1-11eb-97d7-7852c75fb29c.png)

**Comment by andweeb** [comment]
Ah gotcha, no worries! Thanks for letting me know, I don't think I've seen that before, maybe it's particular to Windows? I'll spin up my vm when I have the time and check out the behavior (I primarily use macOS).

> ...it doesn't detect any socket address for my neovim session

Is that in reference to the "Got nvim socket addresses: {}" log or is there another log that states "Failed to get Discord IPC socket"? The latter would indicate the Discord IPC socket wasn't able to be found on your system (which of course would cause Rich Presence to not work), but the former would be a non-issue.

Is Rich Presence not working in general when you're running nvim using `cmd`? I don't think I've tested the plugin with `cmd` before, only with Powershell and Alacritty.

**Comment by hypadr1v3** [comment]
Rich presence does not work in general on cmd. The screenshot above is all the logs I get if I use cmd. I will test on PowerShell and cygwin if I get time.

**Comment by hypadr1v3** [comment]
PowerShell, cygwin64 and mingw64  have the same behavior as cmd

**Comment by hypadr1v3** [comment]
My guess is that on command line, your FocusGained event doesn't trigger and thus it never decides to authorize with discord.

**Comment by andweeb** [comment]
Interesting, yeah it doesn't seem like in your screenshots the event is being triggered at all. Thanks for the tip! Sorry for the late response, I haven't had time to look into this yet but I should have time this week!

**Comment by andweeb** [comment]
Oh wow it looks I misunderstood the `FocusGained` event due an [existing bug](https://github.com/neovim/neovim/issues/14572) with autocmds _incorrectly_ being triggered on startup within tmux. I had assumed that that was the correct behavior in any environment (I only ever use tmux!).

Looks like I'll need to re-introduce the `BufAdd` autocmd to correctly set user activity when opening a new file. Thanks so much for reporting this!

**Comment by andweeb** [comment]
@hypadr1v3 I've just pushed a fix so you should be able to see Rich Presence on initial nvim startup after you update your plugins.

This issue wasn't actually Windows-specific so I ran some smoke tests to make sure things were working as expected in macOS and Ubuntu (without tmux) along with Windows, but let me know if you still have issues.

Thanks again! :)

**Comment by hypadr1v3** [comment]
All right! This makes sense as I mainly use xterm or ConEmu for console emulation.
