### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by rambip** [andweeb/presence.nvim#21]
My last presence plugin (https://github.com/ObserverOfTime/discord.nvim), even if it was slower and less configurable, seemed to have more icons and programming languages available.
For example, a .ino file (for arduino) does not seem to be supported.

I'm not sure how they did it in the previous plugin, but they used this repository:
https://github.com/file-icons/icons

So it would be really cool if this plugin could support arduino !

**Comment by rambip** [comment]
This image could do it for example:
![](http://rarecomponents.com/store/image/data/0-Arduino-icon.png)

**Comment by andweeb** [comment]
Hi @rambip! Thanks for sharing, I wasn't aware of this fork! Seems like the project makes use of quite a lot of various icon sources at least according to their README.

I can sift through to see which file types presence.nvim is missing relative to this fork, but I can start by adding your `.ino` file. Any others you'd like me to add?

**Comment by andweeb** [comment]
I've added support for `.ino` Arduino files in ff59650 so I'll close out this issue!

I'll look into supporting a more comprehensive set of filetypes when I have the time with file-icons (I've added a card [here](https://github.com/andweeb/presence.nvim/projects/1#card-63029092)). Otherwise feel free to re-open with any other specific files you'd like support for!

**Comment by rambip** [comment]
I was thinking about a few functional programming languages: 

- idris
![](https://cdn.icon-icons.com/icons2/2107/PNG/512/file_type_idris_icon_130535.png)

- scheme
![](https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Lambda_lc.svg/1280px-Lambda_lc.svg.png)

- common lisp
![](https://img-premium.flaticon.com/png/512/919/919848.png?token=exp=1623657712~hmac=82e2ac687641ba363ed0a0e4e26604dc)

But otherwise, the languages supported are already pretty impressive, great work !

**Comment by rambip** [comment]
Thanks for the fast commit @andweeb !
But I don't understand, you didn't add the png file in the dropbox folder ?

Can we reopen the issue ?

**Comment by andweeb** [comment]
Oops you're right nice catch, I forgot to enable Dropbox file syncing last night so you should be able to see the assets in the folder now.

I've added the Idris, Scheme, and Common Lisp assets as well, can you check if Rich Presence for those files is working properly? FYI I used [this](https://www.dropbox.com/sh/j8913f0gav3toeh/AADxjn0NuTprGFtv3Il1Pqz-a?dl=0&preview=lisp.png) asset for lisp file types.
