### ISSUE TITLE
Suddenly stops

### ISSUE THREAD

**Issue by foodornt** [andweeb/presence.nvim#23]
The rich presence suddenly disappears, how can I debug that?

Also, any commands to restart the plugin?

**Comment by andweeb** [comment]
Hi @foodornt! By disappearing do you mean Rich Presence in Discord unexpectedly goes away despite having nvim still open? Do you have any particular reproducible steps for this?

You can check out the [Troubleshooting section](https://github.com/andweeb/presence.nvim#troubleshooting) in the README for debugging information.

There's no explicit way to restart the plugin, but you can force update your Rich Presence with the command:
```
:lua package.loaded.presence:update()
```

Let me know how to reproduce this issue, and paste the logs here for me to help you out!

**Comment by foodornt** [comment]
Works perfectly now, I didn't do `require` so I guess that's the reason
