### ISSUE TITLE
Nvim hangs after closing if Telescope is opened while Presence is running but Discord isn't

### ISSUE THREAD

**Issue by Groctel** [andweeb/presence.nvim#24]
Hi! This is the weirdest issue I've ever written. Let's give it a try!

First of all, [here are my dotfiles](https://github.com/Groctel/dotfiles/tree/main/files-common/.config/nvim) in case you want to try them to replicate the error. Here's how to reproduce the error:

- Open an nvim session with Presence and Telescope plugins while there are no Discord processes runing.
- Open **any** Telescope window (like `Telescope find_files`).
- Close the Telescope window either by escaping or by selecting a result.
- Quit nvim.
- The interface closes but the process in hung indefinitely and has to be `^C` killed.

I've tried opening Discord to see the plugin's output when using Telescope but I've found that it doesn't hang after closing if Discord is open. What's also curious is that it doesn't hang if I open Discord **before** opening Telescope. My guess here is that Presence is trying to keep the RPC connection open or that it can't close it at all, but that's just a hunch.

I know this is a very weird edge case, so don't worry if it can't be fixed or it's set as the lowest priority issue :)

**Comment by andweeb** [comment]
Wow uhhh this is a very specific, strange, and (if consistent) a pretty high-priority issue (having to `^C` after exiting kinda sucks!). I also use Telescope but I guess I've never run into this due to having Discord always run on startup. Is it only with Telescope that causes this issue, and not simply opening any other (floating) windows or using other plugins?

I'll be traveling for the next couple days so I may not be able to resolve this until next week, but let me know if you discover any other related edge cases or if you have any ideas on why this may be happening. I'll get back to you sooner if I find the time, thanks for the thorough report!

**Comment by Groctel** [comment]
Thanks for the reply! I was so baffled about the weirdness of this issue that I forgot I had [Floaterm](https://github.com/voldikss/vim-floaterm) installed, which ["Support neovim floatwin and vim8 popupwin"](https://github.com/voldikss/vim-floaterm#features). It turns out that opening a floating terminal also makes nvim hang just like opening Telescope, so the bug seems to be related to popup windows.

Don't worry about the time to fix it. Enjoy your trip!

**Comment by andweeb** [comment]
Thanks for your patience @Groctel! It looks like it was introduced in f4c1e22 with the re-addition of the `BufEnter` autocommand to resolve #19.

For some reason it looks like Telescope triggers the event _four_ times at once, and I'm assuming that holds true for any popup window if you've observed the same behavior with Floaterm. It's most likely that the multiple simultaneous writes to the socket causes the pipe handle to somehow hang after terminating Neovim, even though there's never a connection made (as Discord isn't running).

I don't see a workaround for this at the moment :( I'll let you know when I've come out with a fix!

**Comment by andweeb** [comment]
@Groctel I've just pushed 774994a which should fix the issue :) Feel free to reopen if you still have issues after updating your plugin!

**Comment by Groctel** [comment]
Hi! Sorry for not responding yesterday. I've gotten a lot of work all of the sudden and haven't had time to respond :((
I can confirm that the program is not hanging after closing anymore. Thank you very much for your time and work!!!
