### ISSUE TITLE
[feature] Add pgsql icon

### ISSUE THREAD

**Issue by foodornt** [andweeb/presence.nvim#29]
Something like [this](https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Postgresql_elephant.svg/1200px-Postgresql_elephant.svg.png) should suffice.

![image](https://user-images.githubusercontent.com/40924367/126212093-5c106f94-4600-4450-b1b5-02acc12ab894.png)

**Comment by andweeb** [comment]
Sure! This would only be for `pgsql` file extensions right?

**Comment by foodornt** [comment]
> This would only be for `pgsql` file extensions right?

Yes I think so

**Comment by andweeb** [comment]
Cool, done! :) FYI Discord may take a little while to refresh the cache, it should show up within 10-15 min.

**Comment by foodornt** [comment]
> Cool, done! :) FYI Discord may take a little while to refresh the cache, it should show up within 10-15 min.

That was quick! Thank you!
