### ISSUE TITLE
Yaml files support

### ISSUE THREAD

**Issue by devanlooches** [andweeb/presence.nvim#3]
Hello I was just wondering if you could add yaml support because I don't see it in the asset folder.

Thank you

**Comment by andweeb** [comment]
Sure! Do you have a link to a logo asset in svg or png?

**Comment by devanlooches** [comment]
![yaml](https://user-images.githubusercontent.com/50296057/110829788-5da32e00-824d-11eb-8d54-6bc0edafa20b.png)
Possibly this one. Also I just thought of another file exstension you can support: .abook with the following image maybe:
![abook](https://user-images.githubusercontent.com/50296057/110829907-7ad7fc80-824d-11eb-80c7-c30bf5f9f77e.jpeg)

**Comment by devanlooches** [comment]
actually maybe this one is better for yaml:
![yaml](https://user-images.githubusercontent.com/50296057/110830045-a6f37d80-824d-11eb-90ff-4e7ea390cb70.png)

**Comment by andweeb** [comment]
Okay, just uploaded the two assets to Discord!

What should the name be for `.abook` files? The name will appear when you hover over the file asset in the Rich Presence display.

**Comment by devanlooches** [comment]
hmm maybe just abook is fine

**Comment by devanlooches** [comment]
Great thanks!

**Comment by devanlooches** [comment]
oh also it should be for not only .abook files but probably also for files named addressbook

**Comment by andweeb** [comment]
Oh okay, should the name can be "Address Book"? Just to confirm it'll be any of the following files:
* files with `.abook` extension
* file with `addressbook` file name
* file with `abookrc` file name

**Comment by devanlooches** [comment]
I atually don't think the .abook one exists its mostly the last to.

**Comment by andweeb** [comment]
Alrighty, just pushed the changes! You can update the plugin now but FYI it may take Discord a while to actually update the asset changes (they seem to take about 10-30 minutes and require a reload of the app).

**Comment by andweeb** [comment]
Actually it looks like it's working now!
<img width="244" alt="Screen Shot 2021-03-11 at 10 30 35 AM" src="https://user-images.githubusercontent.com/10726590/110836423-e1ace400-8254-11eb-9b3b-f0f92f23178f.png">
<img width="272" alt="Screen Shot 2021-03-11 at 10 30 48 AM" src="https://user-images.githubusercontent.com/10726590/110836421-e07bb700-8254-11eb-833b-e3ae21286685.png">

**Comment by devanlooches** [comment]
Great thank you!!!!

**Comment by devanlooches** [comment]
Hmm it actually doesn't seem to work for me :(

**Comment by andweeb** [comment]
If updating the plugin and reloading the app didn't work, you may need to explicitly reset the cache by the steps outlined here: https://github.com/discord/discord-rpc/issues/21#issuecomment-344508685.

Otherwise you might just have to wait, Discord is a little weird with its asset caching system. 🤷

**Comment by devanlooches** [comment]
Oh right thank you for reminding me I forgot to update the plugin (oopsie)

**Comment by devanlooches** [comment]
yup it works now thanks!
