### ISSUE TITLE
[Error] Error executing vim.schedule lua callback: Vim:E731: using Dictionary as a String

### ISSUE THREAD

**Issue by TornaxO7** [andweeb/presence.nvim#30]
I'm getting the following error again and again, if I start using `presence.nvim`:

```
Error executing vim.schedule lua callback: Vim:E731: using Dictionary as a String
```

which is pretty annoying. Here are my settings:

```lua
local presence = require("presence")

presence:setup ({
    auto_update         = true,
    neovim_image_text   = "Vimming makes fun :)",
    main_image          = "neovim",
    client_id           = "793271441293967371",
    log_level           = nil,
    debounce_timeout    = 10,
    enable_line_number  = true,

    -- Rich Presence text options
    editing_text        = "Vimming %s",
    file_explorer_text  = "Browsing %s",
    git_commit_text     = "Committing changes",
    plugin_manager_text = "Managing plugins",
    reading_text        = "Reading %s",
    workspace_text      = "Working on %s",
    line_number_text    = "Line %s out of %s",
})
```

**Comment by andweeb** [comment]
Hmm that error shouldn't be happening after what I've pushed in a683551 after addressing it in #28. Unfortunately I had some trouble replicating it, I guess the change still didn't fix it.

Can you confirm that you've been using the most up-to-date presence.nvim plugin and provide your OS information and Neovim version?

It would also help me to look at your logs. Can you enable logging and paste them here? You can set add `log_level = "debug"` to your setup call in Lua and load a file and inspect the logs with `:messages`.

Sorry for the error :/ That does sound pretty annoying.

**Comment by TornaxO7** [comment]
> It would also help me to look at your logs. Can you enable logging and paste them here? You can set add log_level = "debug" to your setup call in Lua and load a file and inspect the logs with :messages.

So this are my settings now at the moment:
```lua
local presence = require("presence")

presence:setup ({
    auto_update         = true,
    neovim_image_text   = "Vimming makes fun :)",
    main_image          = "neovim",
    client_id           = "793271441293967371",
    log_level           = nil,
    debounce_timeout    = 10,
    enable_line_number  = true,

    -- Rich Presence text options
    editing_text        = "Vimming %s",
    file_explorer_text  = "Browsing %s",
    git_commit_text     = "Committing changes",
    plugin_manager_text = "Managing plugins",
    reading_text        = "Reading %s",
    workspace_text      = "Working on %s",
    line_number_text    = "Line %s out of %s",
    log_leve = "debug",
})
```

And the only error I get, when opening `:messages` is this:
```
Error executing vim.schedule lua callback: Vim:E731: using Dictionary as a String
```

# Reproduction
I think, that I found a way to reproduce it now:
1. Install the [fzf.vim](https://github.com/junegunn/fzf.vim) plugin
2. Open any file
3. Open and close fzf again and again (with `:Files` for example) then the error should occur after some time.

So I think that there something like a collision with this plugin I guess? I can't test it at the moment, because `presence.nvim` doesn't even starts (my discord status doesn't show up with neovim)?

**Comment by andweeb** [comment]
Okay wow that was a real sneaky issue, it actually had to do with issues with decoding the response from Discord, not from invalid log messages as I suspected in #28.

I was actually able to replicate it using your exact setup, thanks so much for providing details! For some reason the error doesn't appear when not having the plugin configured (my personal config doesn't configure presence.nvim), which explains why I wasn't able to replicate it before.

I'm still not exactly sure why it's only for certain cases in which parsing responses fail, but now with better exception handling in f2a0dd5 the plugin should not longer throw those annoying errors.

Of course if you still observe these annoying errors please feel free to reopen the issue and I'll look further into it. Thanks again! :)
