### ISSUE TITLE
.org file icon (org-mode)

### ISSUE THREAD

**Issue by foodornt** [andweeb/presence.nvim#37]
looks like this
![org mode icon](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Org-mode-unicorn.svg/1200px-Org-mode-unicorn.svg.png)

**Comment by andweeb** [comment]
Done! Should look like this for any `.org` file depending on your `main_image` config:
<img width="186" alt="Screen Shot 2021-09-28 at 4 56 00 PM" src="https://user-images.githubusercontent.com/10726590/135181110-2f2fd5cd-5996-436f-9af5-197d8425a573.png">
<img width="188" alt="Screen Shot 2021-09-28 at 4 55 37 PM" src="https://user-images.githubusercontent.com/10726590/135181111-b4346e2f-ecca-4e7d-b4dd-10bbd92da429.png">

**Comment by foodornt** [comment]
Much appreciated!
