### ISSUE TITLE
Error when installing the plugin

### ISSUE THREAD

**Issue by isaacsa51** [andweeb/presence.nvim#4]
As title says, new using neovim, but when I run/install again the plugin shows this error:

![image](https://user-images.githubusercontent.com/43853643/111039905-dccf6800-83ed-11eb-9f38-9af6b77e2364.png)

I didn't change anything or configure anything because it should work out of the box.

_Any solution for this?_

**Comment by andweeb** [comment]
Are you using [Neovim nightly (v0.5)](https://github.com/neovim/neovim/releases/tag/nightly)? The plugin makes use of a lot of major improvements to the Lua API in v0.5, including that global dictionary `vim.g`, so it requires the pre-release version of Neovim.

I get a similar error when using the latest version (v0.4.4):
<img width="834" alt="Screen Shot 2021-03-13 at 11 00 18 AM" src="https://user-images.githubusercontent.com/10726590/111041078-4ef27d80-83eb-11eb-863c-c0640c60c02f.png">

**Comment by isaacsa51** [comment]
Oops, didn't read that part when I need to use the nightly version of Neovim, thanks a lot man, it's fixed
