### ISSUE TITLE
Does not appear in Discord

### ISSUE THREAD

**Issue by Yoliani** [andweeb/presence.nvim#41]
![image](https://user-images.githubusercontent.com/70610879/139355916-23ca0250-2d21-43e4-8e37-be3259b702bc.png)
![image](https://user-images.githubusercontent.com/70610879/139356001-07da13cb-9394-4bc7-b527-59b8504575d2.png)

![image](https://user-images.githubusercontent.com/70610879/139356129-510280a9-d75c-4c59-9b09-6c1a52ab89ed.png)

**Comment by andweeb** [comment]
There's an issue on your end with authorizing with Discord, similar to #38. It looks like I'm missing the beginning part of the logs that contains OS information, can you provide those details?

**Comment by Yoliani** [comment]
I had to leave the default settings
