### ISSUE TITLE
[Flatpak] Add link to adding RPC for Flatpak Discord client

### ISSUE THREAD

**Issue by ethanholz** [andweeb/presence.nvim#45]
Please add the following to link to the README or Flatpak to show how to enable RPC for a Flatpak of Discord. I recognize that people can just find this but it would be helpful to have it for new users. Please view the following for more information for this flatpak: [https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)](https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)).

**Comment by andweeb** [comment]
Hi @ethanholz good call!

I've added the link to the flatpak instructions to the README and also generalized it a bit for folks that may be using snap or others. Thanks!

**Comment by jiriks74** [comment]
It's now fixed in #129 - you don't need to do some workaround anymore as long as it gets merged.
Before it does you can checkout the pull request.
