### ISSUE TITLE
Show the last active instance instead of the oldest one

### ISSUE THREAD

**Issue by ModProg** [andweeb/presence.nvim#46]
It would be great if it would automatically switch to the currently active instance (maybe after some time of editing the new file) even when the old file is still open in another instance of neovim.

**Comment by andweeb** [comment]
Hi @ModProg! Are you using Windows? That feature should already be supported in Linux and macOS, but hasn't yet been implemented in Windows (you can see an existing card for it [here](https://github.com/andweeb/presence.nvim/projects/1#card-60537963)).

**Comment by ModProg** [comment]
> Hi @ModProg! Are you using Windows? That feature should already be supported in Linux and macOS, but hasn't yet been implemented in Windows (you can see an existing card for it [here](https://github.com/andweeb/presence.nvim/projects/1#card-60537963)).

I am on Linux, I'll update later and have a look if it still happens.

**Comment by ModProg** [comment]
Still happens. I opened nvim in one terminal and it showed it correctly in Discord. I then created a new terminal and minimized the other instance and started working on another project in nvim.

It was still showing the old file and project in discord.

**Comment by andweeb** [comment]
Hi @ModProg, sorry for the late response! I've just recently added an issue template for bugs and errors, would you mind providing the details outlined [here](https://github.com/andweeb/presence.nvim/issues/new?assignees=&labels=bug&template=bug_report.yml), or close this issue and re-open with that new issue template?

Once I have the steps to reproduce with your OS information I should be able to help you out :)

**Comment by ModProg** [comment]
Now with the template here: #59
