### ISSUE TITLE
Cargo file support, update Rust and Toml image

### ISSUE THREAD

**Issue by cpea2506** [andweeb/presence.nvim#51]
## Preview: 

<div align="center">
    <img width="256px" src="https://github.com/cpea2506/nvim-discord-presence-assets/blob/main/rust.png?raw=true" />
    <img width="256px" src="https://github.com/cpea2506/nvim-discord-presence-assets/blob/main/cargo.png?raw=true" />
    <img width="256px" src="https://github.com/cpea2506/nvim-discord-presence-assets/blob/main/toml.png?raw=true" />
</div>

---

- The Rust image was from [vscode-discord-assets](https://github.com/smokes/vscode-discord-assets)
- The Toml and Cargo image was made by me. For Cargo, it's under the [Rust Trademark policy](https://www.rust-lang.org/policies/media-guide)

## Some note

As the title, i just made my own a place to save my custom assets for this repo. These image can be taken from [drive](https://drive.google.com/drive/u/2/folders/1rJLJG7NY2Esuef9tnABKhUlA5zfFHyaM) or [github](https://github.com/cpea2506/nvim-discord-presence-assets). It would be appreciate if you could take a look and update what is missing or change some default images.

Also, here is the `client_id` for anyone who want to see my custom image: `914799712794705961`. Ye! only files that are currently supported works. 😂

Thanks!

**Comment by foodornt** [comment]
vouch

**Comment by cpea2506** [comment]
> vouch

Ah, maybe there are some misunderstandings here. I just want someone to support these features.

**Comment by foodornt** [comment]
yes, vouch means that exactly, I want it to be supported as well

**Comment by andweeb** [comment]
Sorry for the late response folks! I've added the cargo art asset for the default Discord application and updated the art asset for the Rust logo (and updated a couple other dark logos without a background).

@cpea2506 A user informed me of a new Discord feature to [allow specifying image URLs](https://github.com/andweeb/presence.nvim/issues/11#issuecomment-1011899498), so with that I've just added support to enable custom file assets in #11. With that you should be able to configure any unavailable file types or custom art assets you want to use in addition to or in place of the existing default file assets.

A tracked repository for these assets sounds like a really good idea! That could allow for better collaboration and discussions on particular art assets, and in general moving away from DIscord's clunky art asset upload UI sounds really appealing :) I'll consider having an official asset collection repository for presence.nvim, but I'll need to see whether the image URL functionality is an official one.

**Comment by cpea2506** [comment]
Love it. Thank you very much <3
