### ISSUE TITLE
Presence not updating when switching to another vim instance in a different tmux session

### ISSUE THREAD

**Issue by Gilgames000** [andweeb/presence.nvim#52]
Hey! Loving the plugin so far. The only issue I'm having is that the presence is not updating when I switch to another vim instance in a different tmux session even after editing a file. Did I misunderstand how this should work? If I close the first vim instance I opened the presence updates accordingly though. Thanks!

**Comment by andweeb** [comment]
Hi @Gilgames000, sorry for the late response!

You're right in that the presence should update when you switch to another instance in a different tmux session.

Can you provide your OS information and enable logging and paste the messages of both Neovim instances?

**Comment by andweeb** [comment]
Oh interesting, looks like there's an issue with retrieving peer nvim sockets in Arch Linux via `netstat`, as #59 was reported by a user also using Arch Linux.

I'll mark this issue as a duplicate in favor of #59 considering it's technically older (re-up of #46). Thanks for posting the logs @Gilgames000! I'll move these to the other issue and follow up there.
