### ISSUE TITLE
Clicking View Repository on Discord not opening in browser.

### ISSUE THREAD

**Issue by Crazypersonalph** [andweeb/presence.nvim#66]
### Description

Clicking view repository within Discord is not doing anything. My repo is on github, so it is not opening on github either.

EDIT: It works in a browser, but not in the Discord App.

### Neovim version

```markdown
NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az152-430
```

### OS information

Windows 11 Home Insider Build 22593.ni_release.220402-1100

### Steps to reproduce

1. Setup presence.nvim with default settings.
2. Open any file that has a git repository attached to it.
3. Go onto your profile on Discord

### Logs

C:\Users\helpm\Desktop
C:\Users\helpm\Desktop\why
C:\Users\helpm
C:\Users\helpm\Desktop
C:\Users\helpm\Desktop\Code and Game Dev
C:\Users\helpm\Desktop\Code and Game Dev\AJ-OS
C:\Users\helpm\Desktop\Code and Game Dev\AJ-OS\src
E492: Not an editor command: impl
C:\Users\helpm\Desktop\Code and Game Dev\AJ-OS\src\impl
C:\Users\helpm\Desktop\Code and Game Dev\AJ-OS\src\impl\kernel
E492: Not an editor command: neovim --version
E492: Not an editor command: messagew

**Comment by l-zeuch** [comment]
This is an issue with Discord themselves, rather than the plugin.

They simply do not allow you to click on your buttons on your presence.
