### ISSUE TITLE
[EndeavourOS / Arch Linux] Opening file with NERDTree does not work 

### ISSUE THREAD

**Issue by awyxx** [andweeb/presence.nvim#8]
Hi again :) Okay so im having another issue now D:
Running only `nvim` and selecting the file I want to edit with the NERDTree plugin, I get this error

`[presence.nvim] Activity already set for /home/roby/NERD_tree_1, skipping...
[presence.nvim] Activity already set for /home/roby/NERD_tree_1, skipping...
[presence.nvim] Activity already set for /home/roby/NERD_tree_1, skipping...
[presence.nvim] Setting activity for /home/roby/frontend/tests/e2e/specs/files/avatar.spec.js...
[presence.nvim] Parsed filename avatar.spec.js with js extension
[presence.nvim] Using file asset: { "JavaScript", "javascript" }
[presence.nvim] Detected project: frontend
[presence.nvim] Failed to set activity in Discord: Pipe write error - EPIPE
[presence.nvim] Pipe was closed
Press ENTER or type command to continue`

Running `nvim frontend/tests/e2e/specs/file.js` worked tho! 
Is there anyway to make it work with the NERDTree aswell?

**Comment by andweeb** [comment]
Hi again @awyxx! Ooh interesting, I personally don't use any file system explorer plugins (nerdtree, netrw, etc.) so I've never tested this out locally. I'll try it out myself to see if I can replicate the error.

Would you have an idea of what an expected behavior would be in that scenario? Should there be a Rich Presence update for NERDTree or something like that? Or do you just expect there not to be an error?

**Comment by andweeb** [comment]
It doesn't seem like I can replicate that error in macOS, but it does send a Rich Presence update when it probably shouldn't.. at least the way it does right now:
<img width="602" alt="Screen Shot 2021-04-30 at 7 42 38 PM" src="https://user-images.githubusercontent.com/10726590/116768555-39adce80-a9ec-11eb-8e76-5ac4698498c1.png">

It looks like NERDTree uses a buffer name `NERD_tree_1`, so it looks like `presence.nvim` thinks you're "editing" NERDTree's split window. 🥲

So it looks like there's a couple things here:
* Unexpected error in EndeavorOS (maybe Linux in general or at least Arch Linux) 
* Unexpected/invalid Rich Presence update in macOS (maybe all platforms that don't run into the first error)

**Comment by awyxx** [comment]
`
[presence.nvim] Setting up plugin...
[presence.nvim] Completed plugin setup
[presence.nvim] Getting nvim socket addresses...
[presence.nvim] Custom setup not detected, using defaults
[presence.nvim] Got nvim socket addresses: {}
[presence.nvim] No other remote nvim instances
` I get this error sometimes, but for some reason, it works for me aswell now.

**Comment by andweeb** [comment]
Hmm yeah it also seemed to work in my Arch Linux vm, so it may have just been an ephemeral communication issue with Discord. If you run into the error again, feel free to re-open this issue and let me know how to reproduce the error!

I'll make a note to improve the Rich Presence activity when using NERDTree and other file explorers. Thanks!

**Comment by awyxx** [comment]
Alright, it works most of the timer for me now tho, so its fine!
Thanks for the support! :smile:
