### ISSUE TITLE
attempt to call method 'set_option' (a nil value)

### ISSUE THREAD

**Issue by bellini666** [andweeb/presence.nvim#90]
### Description

Failed to run `config` for presence.nvim

...ocal/share/nvim/lazy/presence.nvim/lua/presence/init.lua:76: attempt to call method 'set_option' (a nil value)

# stacktrace:
  - /presence.nvim/lua/presence/init.lua:76 _in_ **setup**

### Neovim version

```markdown
NVIM v0.9.0-dev-710+gef89f9fd4
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by bellini@loki
```

### OS information

Debian Unstable

### Steps to reproduce

1. Setup the plugin using lazy.nvim package manager like:

```lua
{
  "andweeb/presence.nvim",
  config = true,
  event = "VeryLazy",
},
```

The config can be a function that calls `require("presence").setup({})`, the error will still be the same

2. Open nvim
3. The error will show up

### Logs

Failed to run `config` for presence.nvim

...ocal/share/nvim/lazy/presence.nvim/lua/presence/init.lua:76: attempt to call method 'set_option' (a nil value)

# stacktrace:
  - /presence.nvim/lua/presence/init.lua:76 _in_ **setup**

**Comment by bellini666** [comment]
Oh, I see now where it went wrong. The setup function is called with `:` and not `.`.

Would be nice to have a `.` option as well, because it is the pattern used by most (if not all) other plugins.

Also, it makes it possible to use the short `config = true` or `opts: {...}` in lazy.nvim

**Comment by andweeb** [comment]
Hi @bellini666! Thanks for the call out. I did recall there was [another issue](https://github.com/andweeb/presence.nvim/issues/54) with the same confusion from a couple users, so I finally got around to addressing this. I don't personally use lazy.nvim so I didn't realize the colon syntax would introduce potential limitations like that.

I've just pushed a change that supports calls to the setup function that use the traditional dot syntax, so I'll close this issue. I've tested it locally but haven't tried it out using lazy.nvim. Let me know if you run into any issues!

**Comment by bellini666** [comment]
Hey @andweeb , it is working now, thank you!

The only issue that I'm noticing now is this: https://github.com/andweeb/presence.nvim/issues/91

It used to work before, but is not working anymore. Don't think it has anything to do with your change
