### ISSUE TITLE
Presence only starts working after running a different plugin

### ISSUE THREAD

**Issue by ghost** [andweeb/presence.nvim#96]
### Description

**Problem:** Discord presence only shows on discord after running something like Telescope, PackerSync, PackerInstall, etc..

### Neovim version

```markdown
NVIM v0.9.0-dev-1051+g1d8b77da6
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### OS information

Ubuntu 22.04

### Steps to reproduce

1. Install plugin using packer:   use ('andweeb/presence.nvim')
2. Run setup in after/plugin/presence.lua:  require('presence').setup()
3. Open Discord
4. Open any file with vim: vim app.js
5. Nothing shows on Discord
6. Run :PackerSync, :PackerInstall or Telescope
7. Presence starts showing on Discord until you close neovim

### Logs

![image](https://user-images.githubusercontent.com/78612129/228307268-e348085e-f6e1-4ae8-a86c-5b2748b6ab24.png)

**Comment by ghost** [comment]
A couple of things I forgot to mention: 

- The first time I open a file with neovim it works fine, but after I close neovim and open another file, it doesn't work.
- It stays on for around ~15 seconds after closing neovim.
- Sometimes it stops working completely, even after running PackerStatus or Telescope.

This is the log when it works fine on nvim start:
 
![image](https://user-images.githubusercontent.com/78612129/228322161-85efef7d-0868-465f-92ee-148d482430c3.png)

**Comment by ghost** [comment]
Log when presence starts working after running Telescope: 

![image](https://user-images.githubusercontent.com/78612129/228324554-2b20e6a3-37b2-463d-b9d9-90c73a823a09.png)

**Comment by ghost** [comment]
I found out that the problem was in the function `presence:update_for_buffer` 
after removing this: 

```lua
if self.options.enable_line_number == 0 and self.last_activity.file == buffer then
        self.log:debug(string.format("Activity already set for %s, skipping...", buffer))
        return
    end
```

It works fine all the time. I don't know if removing the whole conditional* is a good approach and I don't know either why it would skip setting the presence for files opened for the first time in the current session.

**Comment by goldenbergdaniel** [comment]
I am using macOS and have the same problem. I have to run a command like "PackerSync" or "Explore" in order to get the discord presence working every time I open a new instance of Neovim.

**Comment by ghost** [comment]
in case anyone still has this problem, I forgot to specify to which file you need to make the edits above, go to: `~/.local/share/nvim/site/pack/packer/start/presence.nvim/lua/presence/ ` and then open the file `init.lua` removing the lines I said above:  https://github.com/andweeb/presence.nvim/issues/96#issuecomment-1494242233
